name: "Test & Lint"

on:
    pull_request:
        branches: 
            - develop
            - main

jobs:
    test:
        name: "Test"
        runs-on: macos-latest

        steps:
            # Checkout repository
            -   name: Checkout Repository
                uses: actions/checkout@v4
        
            # Setup flutter
            -   name: Setup Flutter
                uses: subosito/flutter-action@v2
                with:
                    flutter-version: '3.19.4'
                    channel: 'stable'

            # Install dependencies
            -   name: Install dependencies
                run: flutter pub get

            # Run tests
            -   name: Run app tests
                run: flutter test
    lint:
        name: "lint"
        runs-on: macos-latest

        steps:
            # Checkout repository
            -   name: Checkout Repository
                uses: actions/checkout@v4
        
            # Setup flutter
            -   name: Setup Flutter
                uses: subosito/flutter-action@v2
                with:
                    flutter-version: '3.19.4'
                    channel: 'stable'

            # Install dependencies
            -   name: Install dependencies
                run: flutter pub get

            # Run lint
            -   name: Run lint
                run: dart analyze
